export interface MasterRecord {
  srNo: number;
  facultyName: string;
  className: string;
  divisionName: string;
  batchName: string;
  location: string;
  courseCode: string;
  courseName: string;
  theory: number;
  practical: number;
  tutorial: number;
  project: number;
  total: number;
  allowedLocationsList: { batch: string; roomNumber: string; isPreferred?: boolean }[];
}

export const CANONICAL_168_DATA: MasterRecord[] = [
  {
    srNo: 1,
    facultyName: 'Dr. M. V. Kadam',
    className: 'BE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: '410241',
    courseName: 'Design and Analysis of Algorithms',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 2,
    facultyName: 'Dr. M. Y. Dangore',
    className: 'BE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: '410242',
    courseName: 'Machine Learning',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 3,
    facultyName: 'Prof. Y. B. Dongare',
    className: 'BE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: '410243',
    courseName: 'Blockchain Technology',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 4,
    facultyName: 'Dr. Y. V. Patil',
    className: 'BE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: '410244(D)',
    courseName: 'Elective III',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 5,
    facultyName: 'Dr. S. S. Chaudhari (TPC)',
    className: 'BE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: '410245(D)',
    courseName: 'Elective IV',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 6,
    facultyName: 'Dr. M. Y. Dangore',
    className: 'BE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'C102',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'C102', isPreferred: true }, { batch: 'A1', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 7,
    facultyName: 'Prof. D. J. Bonde',
    className: 'BE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'C102',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'C102', isPreferred: true }, { batch: 'A1', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 8,
    facultyName: 'Dr. M. Y. Dangore',
    className: 'BE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'C104',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 9,
    facultyName: 'Prof. D. B. Satre',
    className: 'BE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'C104',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 10,
    facultyName: 'Dr. M. Y. Dangore',
    className: 'BE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'C110',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'C110', isPreferred: true }, { batch: 'A3', roomNumber: 'C102', isPreferred: true }, { batch: 'A3', roomNumber: 'C111', isPreferred: true }]
  },
  {
    srNo: 11,
    facultyName: 'Prof. D. J. Bonde',
    className: 'BE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'C110',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'C110', isPreferred: true }, { batch: 'A3', roomNumber: 'C102', isPreferred: true }, { batch: 'A3', roomNumber: 'C111', isPreferred: true }]
  },
  {
    srNo: 12,
    facultyName: 'Prof. D. B. Satre',
    className: 'BE',
    divisionName: 'A',
    batchName: 'A4',
    location: 'C110',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A4', roomNumber: 'C110', isPreferred: true }]
  },
  {
    srNo: 13,
    facultyName: 'Prof. D. J. Bonde',
    className: 'BE',
    divisionName: 'A',
    batchName: 'A4',
    location: 'C110',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A4', roomNumber: 'C110', isPreferred: true }]
  },
  {
    srNo: 14,
    facultyName: 'Dr. S. S. Chaudhari (TPC)',
    className: 'BE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'C105',
    courseCode: '410247',
    courseName: 'Laboratory Practice IV',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'C105', isPreferred: true }]
  },
  {
    srNo: 15,
    facultyName: 'Dr. Y. V. Patil',
    className: 'BE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'C105',
    courseCode: '410247',
    courseName: 'Laboratory Practice IV',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'C105', isPreferred: true }]
  },
  {
    srNo: 16,
    facultyName: 'Dr. Y. V. Patil',
    className: 'BE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'C108',
    courseCode: '410247',
    courseName: 'Laboratory Practice IV',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 17,
    facultyName: 'Dr. P. B. Dhamdhere',
    className: 'BE',
    divisionName: 'A',
    batchName: 'A4',
    location: 'C104',
    courseCode: '410247',
    courseName: 'Laboratory Practice IV',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A4', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 18,
    facultyName: 'Prof. Niraml B. L.',
    className: 'BE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: '410241',
    courseName: 'Design and Analysis of Algorithms',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 19,
    facultyName: 'Prof. Barangale Shraddha',
    className: 'BE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: '410242',
    courseName: 'Machine Learning',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 20,
    facultyName: 'Prof. P. V. Deshmukh',
    className: 'BE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: '410243',
    courseName: 'Blockchain Technology',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 21,
    facultyName: 'Prof. Nutan Sarode',
    className: 'BE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: '410244(D)',
    courseName: 'Elective III',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 22,
    facultyName: 'Dr. P. B. Dhamdhere',
    className: 'BE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: '410245(C)',
    courseName: 'Elective IV',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 23,
    facultyName: 'Dr. M. Y. Dangore',
    className: 'BE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'C104',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'C104', isPreferred: true }, { batch: 'B1', roomNumber: 'C103', isPreferred: true }, { batch: 'B1', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 24,
    facultyName: 'Prof. M. S. Jagtap',
    className: 'BE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'C104',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'C104', isPreferred: true }, { batch: 'B1', roomNumber: 'C103', isPreferred: true }, { batch: 'B1', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 25,
    facultyName: 'Prof. M. S. Jagtap',
    className: 'BE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'C110',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'C110', isPreferred: true }]
  },
  {
    srNo: 26,
    facultyName: 'Prof. D. J. Bonde',
    className: 'BE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'C110',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'C110', isPreferred: true }]
  },
  {
    srNo: 27,
    facultyName: 'Prof. D. B. Satre',
    className: 'BE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'C111',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'C111', isPreferred: true }, { batch: 'B3', roomNumber: 'C110', isPreferred: true }]
  },
  {
    srNo: 28,
    facultyName: 'Prof. Y. B. Dongare',
    className: 'BE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'C111',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'C111', isPreferred: true }, { batch: 'B3', roomNumber: 'C110', isPreferred: true }]
  },
  {
    srNo: 29,
    facultyName: 'Prof. D. B. Satre',
    className: 'BE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'C110',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'C110', isPreferred: true }]
  },
  {
    srNo: 30,
    facultyName: 'Prof. Y. B. Dongare',
    className: 'BE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'C110',
    courseCode: '410246',
    courseName: 'Laboratory Practice III',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'C110', isPreferred: true }]
  },
  {
    srNo: 31,
    facultyName: 'Dr. Y. V. Patil',
    className: 'BE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'C105',
    courseCode: '410247',
    courseName: 'Laboratory Practice IV',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'C105', isPreferred: true }]
  },
  {
    srNo: 32,
    facultyName: 'Dr. S. S. Chaudhari (TPC)',
    className: 'BE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'C108',
    courseCode: '410247',
    courseName: 'Laboratory Practice IV',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 33,
    facultyName: 'Dr. P. B. Dhamdhere',
    className: 'BE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'C111',
    courseCode: '410247',
    courseName: 'Laboratory Practice IV',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'C111', isPreferred: true }]
  },
  {
    srNo: 34,
    facultyName: 'Dr. Y. V. Patil',
    className: 'BE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'C104',
    courseCode: '410247',
    courseName: 'Laboratory Practice IV',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 35,
    facultyName: 'Dr. S. G. Rathod (HoD)',
    className: 'ME-I',
    divisionName: '-',
    batchName: 'All',
    location: 'E101',
    courseCode: 'PCC-501-COM',
    courseName: 'Probability and Statistics',
    theory: 4,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 4,
    allowedLocationsList: []
  },
  {
    srNo: 36,
    facultyName: 'Dr. M. Y. Dangore',
    className: 'ME-I',
    divisionName: '-',
    batchName: 'All',
    location: 'E101',
    courseCode: 'PCC-502-COM',
    courseName: 'Advanced Algorithms',
    theory: 4,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 4,
    allowedLocationsList: []
  },
  {
    srNo: 37,
    facultyName: 'Dr. S. S. Chaudhari (TPC)',
    className: 'ME-I',
    divisionName: '-',
    batchName: 'All',
    location: 'E101',
    courseCode: 'PCC-503-COM',
    courseName: 'Machine Learning',
    theory: 4,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 4,
    allowedLocationsList: []
  },
  {
    srNo: 38,
    facultyName: 'Dr. S. K. Patil',
    className: 'ME-I',
    divisionName: '-',
    batchName: 'All',
    location: 'E101',
    courseCode: 'PCC-504-COM',
    courseName: 'Distributed Computing',
    theory: 4,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 4,
    allowedLocationsList: []
  },
  {
    srNo: 39,
    facultyName: 'Dr. M. D. Salunke (PG)',
    className: 'ME-I',
    divisionName: '-',
    batchName: 'All',
    location: 'C106',
    courseCode: 'PCC-505-COM',
    courseName: 'Computational Laboratory-I',
    theory: 0,
    practical: 4,
    tutorial: 0,
    project: 0,
    total: 4,
    allowedLocationsList: []
  },
  {
    srNo: 40,
    facultyName: 'Dr. M. D. Salunke (PG)',
    className: 'ME-I',
    divisionName: '-',
    batchName: 'All',
    location: 'E101',
    courseCode: 'PEC-521-COM',
    courseName: 'Elective I',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 41,
    facultyName: 'Dr. J. P. Shinde',
    className: 'ME-I',
    divisionName: '-',
    batchName: 'All',
    location: 'C103',
    courseCode: 'PEC-522-COM',
    courseName: 'Skill Based Laboratory-I',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 42,
    facultyName: 'Dr. J. P. Shinde',
    className: 'ME-I',
    divisionName: '-',
    batchName: 'All',
    location: 'E101',
    courseCode: 'RM-601-COM',
    courseName: 'Research Methodology',
    theory: 4,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 4,
    allowedLocationsList: []
  },
  {
    srNo: 43,
    facultyName: 'Dr. S. G. Rathod (HoD)',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'C105',
    courseCode: 'CEF-260-COM',
    courseName: 'Community Engagement Project',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'C105', isPreferred: true }]
  },
  {
    srNo: 44,
    facultyName: 'Dr. Y. V. Patil',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'C105',
    courseCode: 'CEF-260-COM',
    courseName: 'Community Engagement Project',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'C105', isPreferred: true }]
  },
  {
    srNo: 45,
    facultyName: 'Dr. Y. V. Patil',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'C105',
    courseCode: 'CEF-260-COM',
    courseName: 'Community Engagement Project',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'C105', isPreferred: true }]
  },
  {
    srNo: 46,
    facultyName: 'Dr. S. G. Rathod (HoD)',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A4',
    location: 'C105',
    courseCode: 'CEF-260-COM',
    courseName: 'Community Engagement Project',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A4', roomNumber: 'C105', isPreferred: true }]
  },
  {
    srNo: 47,
    facultyName: 'Dr. M. V. Kadam',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'C102',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'C102', isPreferred: true }, { batch: 'A1', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 48,
    facultyName: 'Dr. M. V. Kadam',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'E101',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 0,
    tutorial: 1,
    project: 0,
    total: 1,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 49,
    facultyName: 'Dr. M. V. Kadam',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'C102',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'C102', isPreferred: true }, { batch: 'A2', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 50,
    facultyName: 'Dr. M. V. Kadam',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'E101',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 0,
    tutorial: 1,
    project: 0,
    total: 1,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 51,
    facultyName: 'Prof. P. V. Deshmukh',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'C111',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'C111', isPreferred: true }, { batch: 'A3', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 52,
    facultyName: 'Prof. P. V. Deshmukh',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'E101',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 0,
    tutorial: 1,
    project: 0,
    total: 1,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 53,
    facultyName: 'Prof. P. V. Deshmukh',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A4',
    location: 'C111',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A4', roomNumber: 'C111', isPreferred: true }, { batch: 'A4', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 54,
    facultyName: 'Prof. P. V. Deshmukh',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A4',
    location: 'E101',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 0,
    tutorial: 1,
    project: 0,
    total: 1,
    allowedLocationsList: [{ batch: 'A4', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 55,
    facultyName: 'Prof. S. A. Agrawal',
    className: 'SE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: 'MDM-230-COM',
    courseName: 'Digital Electronics and Logic Design',
    theory: 2,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 56,
    facultyName: 'Dr. M. V. Kadam',
    className: 'SE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: 'OEL-220-COM',
    courseName: 'Open Elective 1',
    theory: 2,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 57,
    facultyName: 'Prof. D. B. Satre',
    className: 'SE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: 'PCC-201-COMP',
    courseName: 'Data Structures',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 58,
    facultyName: 'Prof. Niraml B. L.',
    className: 'SE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: 'PCC-202-COM',
    courseName: 'Object Oriented Programming and Computer Graphics',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 59,
    facultyName: 'Prof. M. S. Jagtap',
    className: 'SE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: 'PCC-203-COM',
    courseName: 'Operating Systems',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 60,
    facultyName: 'Prof. D. B. Satre',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'C108',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'C108', isPreferred: true }, { batch: 'A1', roomNumber: 'C101', isPreferred: true }]
  },
  {
    srNo: 61,
    facultyName: 'Dr. S. K. Patil',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'C108',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'C108', isPreferred: true }, { batch: 'A1', roomNumber: 'C101', isPreferred: true }]
  },
  {
    srNo: 62,
    facultyName: 'Prof. D. B. Satre',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'C108',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'C108', isPreferred: true }, { batch: 'A2', roomNumber: 'C101', isPreferred: true }]
  },
  {
    srNo: 63,
    facultyName: 'Dr. S. K. Patil',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'C108',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'C108', isPreferred: true }, { batch: 'A2', roomNumber: 'C101', isPreferred: true }]
  },
  {
    srNo: 64,
    facultyName: 'Prof. D. B. Satre',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'C101',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'C101', isPreferred: true }, { batch: 'A3', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 65,
    facultyName: 'Dr. S. K. Patil',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'C101',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'C101', isPreferred: true }, { batch: 'A3', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 66,
    facultyName: 'Prof. D. B. Satre',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A4',
    location: 'C101',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A4', roomNumber: 'C101', isPreferred: true }]
  },
  {
    srNo: 67,
    facultyName: 'Dr. S. K. Patil',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A4',
    location: 'C101',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A4', roomNumber: 'C101', isPreferred: true }]
  },
  {
    srNo: 68,
    facultyName: 'Prof. Niraml B. L.',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'C104',
    courseCode: 'PCC-205-COM',
    courseName: 'Object Oriented Programming and Computer Graphics Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 69,
    facultyName: 'Prof. Niraml B. L.',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'C104',
    courseCode: 'PCC-205-COM',
    courseName: 'Object Oriented Programming and Computer Graphics Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 70,
    facultyName: 'Prof. Niraml B. L.',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'C104',
    courseCode: 'PCC-205-COM',
    courseName: 'Object Oriented Programming and Computer Graphics Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 71,
    facultyName: 'Prof. Niraml B. L.',
    className: 'SE',
    divisionName: 'A',
    batchName: 'A4',
    location: 'C104',
    courseCode: 'PCC-205-COM',
    courseName: 'Object Oriented Programming and Computer Graphics Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A4', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 72,
    facultyName: 'Dr. Y. V. Patil',
    className: 'SE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: 'VEC-250-COM',
    courseName: 'Universal Human Values and Professional Ethics',
    theory: 2,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 73,
    facultyName: 'Prof. S. A. Agrawal',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'C106',
    courseCode: 'CEF-260-COM',
    courseName: 'Community Engagement Project',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'C106', isPreferred: true }]
  },
  {
    srNo: 74,
    facultyName: 'Prof. S. A. Agrawal',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'C106',
    courseCode: 'CEF-260-COM',
    courseName: 'Community Engagement Project',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'C106', isPreferred: true }]
  },
  {
    srNo: 75,
    facultyName: 'Prof. S. A. Agrawal',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'C106',
    courseCode: 'CEF-260-COM',
    courseName: 'Community Engagement Project',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'C106', isPreferred: true }]
  },
  {
    srNo: 76,
    facultyName: 'Prof. S. A. Agrawal',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'C106',
    courseCode: 'CEF-260-COM',
    courseName: 'Community Engagement Project',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'C106', isPreferred: true }]
  },
  {
    srNo: 77,
    facultyName: 'Dr. M. V. Kadam',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'C111',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'C111', isPreferred: true }, { batch: 'B1', roomNumber: 'E104', isPreferred: true }, { batch: 'B1', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 78,
    facultyName: 'Dr. M. V. Kadam',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'E104',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 0,
    tutorial: 1,
    project: 0,
    total: 1,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'E104', isPreferred: true }, { batch: 'B1', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 79,
    facultyName: 'Dr. M. V. Kadam',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'C102',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'C102', isPreferred: true }, { batch: 'B2', roomNumber: 'E104', isPreferred: true }, { batch: 'B2', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 80,
    facultyName: 'Dr. M. V. Kadam',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'E104',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 0,
    tutorial: 1,
    project: 0,
    total: 1,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'E104', isPreferred: true }, { batch: 'B2', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 81,
    facultyName: 'Prof. P. V. Deshmukh',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'C111',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'C111', isPreferred: true }, { batch: 'B3', roomNumber: 'E104', isPreferred: true }, { batch: 'B3', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 82,
    facultyName: 'Prof. P. V. Deshmukh',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'E104',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 0,
    tutorial: 1,
    project: 0,
    total: 1,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'E104', isPreferred: true }, { batch: 'B3', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 83,
    facultyName: 'Prof. P. V. Deshmukh',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'C111',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'C111', isPreferred: true }, { batch: 'B4', roomNumber: 'E104', isPreferred: true }, { batch: 'B4', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 84,
    facultyName: 'Prof. P. V. Deshmukh',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'E104',
    courseCode: 'EEM-240-COM',
    courseName: 'Entrepreneurship Development',
    theory: 0,
    practical: 0,
    tutorial: 1,
    project: 0,
    total: 1,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'E104', isPreferred: true }, { batch: 'B4', roomNumber: 'E101', isPreferred: true }]
  },
  {
    srNo: 85,
    facultyName: 'Prof. U. B. Karanje',
    className: 'SE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: 'MDM-230-COM',
    courseName: 'Digital Electronics and Logic Design',
    theory: 2,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 86,
    facultyName: 'Prof. Y. P. Warke',
    className: 'SE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: 'OEL-220-COM',
    courseName: 'Open Elective 1',
    theory: 2,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 87,
    facultyName: 'Prof. D. J. Bonde',
    className: 'SE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: 'PCC-201-COMP',
    courseName: 'Data Structures',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 88,
    facultyName: 'Prof. Y. B. Dongare',
    className: 'SE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: 'PCC-202-COM',
    courseName: 'Object Oriented Programming and Computer Graphics',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 89,
    facultyName: 'Dr. M. Y. Dangore',
    className: 'SE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: 'PCC-203-COM',
    courseName: 'Operating Systems',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 90,
    facultyName: 'Prof. D. J. Bonde',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'C108',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'C108', isPreferred: true }, { batch: 'B1', roomNumber: 'C102', isPreferred: true }]
  },
  {
    srNo: 91,
    facultyName: 'Prof. U. B. Karanje',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'C108',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'C108', isPreferred: true }, { batch: 'B1', roomNumber: 'C102', isPreferred: true }]
  },
  {
    srNo: 92,
    facultyName: 'Prof. D. J. Bonde',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'C102',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'C102', isPreferred: true }, { batch: 'B2', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 93,
    facultyName: 'Prof. U. B. Karanje',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'C102',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'C102', isPreferred: true }, { batch: 'B2', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 94,
    facultyName: 'Prof. D. J. Bonde',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'C108',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'C108', isPreferred: true }, { batch: 'B3', roomNumber: 'C102', isPreferred: true }]
  },
  {
    srNo: 95,
    facultyName: 'Prof. U. B. Karanje',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'C108',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'C108', isPreferred: true }, { batch: 'B3', roomNumber: 'C102', isPreferred: true }]
  },
  {
    srNo: 96,
    facultyName: 'Prof. D. J. Bonde',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'C102',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'C102', isPreferred: true }, { batch: 'B4', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 97,
    facultyName: 'Prof. U. B. Karanje',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'C102',
    courseCode: 'PCC-204-COM',
    courseName: 'Data Structures Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'C102', isPreferred: true }, { batch: 'B4', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 98,
    facultyName: 'Prof. Y. B. Dongare',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'C104',
    courseCode: 'PCC-205-COM',
    courseName: 'Object Oriented Programming and Computer Graphics Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 99,
    facultyName: 'Prof. Y. B. Dongare',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'C104',
    courseCode: 'PCC-205-COM',
    courseName: 'Object Oriented Programming and Computer Graphics Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 100,
    facultyName: 'Prof. Y. B. Dongare',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'C104',
    courseCode: 'PCC-205-COM',
    courseName: 'Object Oriented Programming and Computer Graphics Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 101,
    facultyName: 'Prof. Y. B. Dongare',
    className: 'SE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'C104',
    courseCode: 'PCC-205-COM',
    courseName: 'Object Oriented Programming and Computer Graphics Laboratory',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 102,
    facultyName: 'Prof. P. V. Deshmukh',
    className: 'SE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: 'VEC-250-COM',
    courseName: 'Universal Human Values and Professional Ethics',
    theory: 2,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 103,
    facultyName: 'Prof. T. S. Bhoye',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'C103',
    courseCode: 'ELC342COM',
    courseName: 'Technical Seminar',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'C103', isPreferred: true }]
  },
  {
    srNo: 104,
    facultyName: 'Prof. Y. P. Warke',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'C105',
    courseCode: 'ELC342COM',
    courseName: 'Technical Seminar',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'C105', isPreferred: true }]
  },
  {
    srNo: 105,
    facultyName: 'Prof. Barangale Shraddha',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'C106',
    courseCode: 'ELC342COM',
    courseName: 'Technical Seminar',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'C106', isPreferred: true }]
  },
  {
    srNo: 106,
    facultyName: 'Prof. Nutan Sarode',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A4',
    location: '-',
    courseCode: 'ELC342COM',
    courseName: 'Technical Seminar',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 107,
    facultyName: 'Prof. Barangale Shraddha',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'C103',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'C103', isPreferred: true }, { batch: 'A1', roomNumber: 'E102', isPreferred: true }]
  },
  {
    srNo: 108,
    facultyName: 'Prof. Barangale Shraddha',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'E102',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 0,
    tutorial: 2,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'E102', isPreferred: true }]
  },
  {
    srNo: 109,
    facultyName: 'Prof. Barangale Shraddha',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'C103',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'C103', isPreferred: true }, { batch: 'A2', roomNumber: 'E102', isPreferred: true }]
  },
  {
    srNo: 110,
    facultyName: 'Prof. Barangale Shraddha',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'E102',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 0,
    tutorial: 2,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'E102', isPreferred: true }]
  },
  {
    srNo: 111,
    facultyName: 'Prof. Nutan Sarode',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'C104',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'C104', isPreferred: true }, { batch: 'A3', roomNumber: 'C108', isPreferred: true }, { batch: 'A3', roomNumber: 'E102', isPreferred: true }]
  },
  {
    srNo: 112,
    facultyName: 'Prof. Nutan Sarode',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'E102',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 0,
    tutorial: 2,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'E102', isPreferred: true }, { batch: 'A3', roomNumber: 'C104', isPreferred: true }, { batch: 'A3', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 113,
    facultyName: 'Prof. Nutan Sarode',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A4',
    location: 'C104',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A4', roomNumber: 'C104', isPreferred: true }, { batch: 'A4', roomNumber: 'E102', isPreferred: true }]
  },
  {
    srNo: 114,
    facultyName: 'Prof. Nutan Sarode',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A4',
    location: 'E102',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 0,
    tutorial: 2,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A4', roomNumber: 'E102', isPreferred: true }, { batch: 'A4', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 115,
    facultyName: 'Dr. S. S. Chaudhari (TPC)',
    className: 'TE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: 'OLE341COM',
    courseName: 'Open Elective',
    theory: 2,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 116,
    facultyName: 'Prof. M. S. Jagtap',
    className: 'TE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: 'PCC301COM',
    courseName: 'Artificial Intelligence',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 117,
    facultyName: 'Dr. M. D. Salunke (PG)',
    className: 'TE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: 'PCC302COM',
    courseName: 'Computer Networks',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 118,
    facultyName: 'Dr. S. K. Patil',
    className: 'TE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: 'PCC303COM',
    courseName: 'Theory of Computation',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 119,
    facultyName: 'Prof. M. S. Jagtap',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'C105',
    courseCode: 'PCC304COM',
    courseName: 'Artificial Intelligence Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'C105', isPreferred: true }]
  },
  {
    srNo: 120,
    facultyName: 'Prof. M. S. Jagtap',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'C105',
    courseCode: 'PCC304COM',
    courseName: 'Artificial Intelligence Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'C105', isPreferred: true }]
  },
  {
    srNo: 121,
    facultyName: 'Prof. M. S. Jagtap',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'C105',
    courseCode: 'PCC304COM',
    courseName: 'Artificial Intelligence Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'C105', isPreferred: true }]
  },
  {
    srNo: 122,
    facultyName: 'Prof. M. S. Jagtap',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A4',
    location: 'C105',
    courseCode: 'PCC304COM',
    courseName: 'Artificial Intelligence Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A4', roomNumber: 'C105', isPreferred: true }]
  },
  {
    srNo: 123,
    facultyName: 'Prof. S. A. Agrawal',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'C101',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'C101', isPreferred: true }]
  },
  {
    srNo: 124,
    facultyName: 'Dr. M. D. Salunke (PG)',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'C101',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'C101', isPreferred: true }]
  },
  {
    srNo: 125,
    facultyName: 'Dr. M. D. Salunke (PG)',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'C102',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'C102', isPreferred: true }, { batch: 'A2', roomNumber: 'C101', isPreferred: true }]
  },
  {
    srNo: 126,
    facultyName: 'Dr. J. P. Shinde',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A2',
    location: '-',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 127,
    facultyName: 'Prof. S. A. Agrawal',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'C101',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'C101', isPreferred: true }, { batch: 'A3', roomNumber: 'C102', isPreferred: true }]
  },
  {
    srNo: 128,
    facultyName: 'Dr. M. D. Salunke (PG)',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A3',
    location: '-',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 129,
    facultyName: 'Dr. M. D. Salunke (PG)',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A4',
    location: 'C101',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A4', roomNumber: 'C101', isPreferred: true }]
  },
  {
    srNo: 130,
    facultyName: 'Prof. S. A. Agrawal',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A4',
    location: '-',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 131,
    facultyName: 'Dr. S. G. Rathod (HoD)',
    className: 'TE',
    divisionName: 'A',
    batchName: 'All',
    location: '-',
    courseCode: 'PEC321COM',
    courseName: 'Elective I',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 132,
    facultyName: 'Prof. U. B. Karanje',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A1',
    location: 'C108',
    courseCode: 'PEC322COM',
    courseName: 'Elective I Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A1', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 133,
    facultyName: 'Prof. U. B. Karanje',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A2',
    location: 'C108',
    courseCode: 'PEC322COM',
    courseName: 'Elective I Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A2', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 134,
    facultyName: 'Prof. U. B. Karanje',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A3',
    location: 'C108',
    courseCode: 'PEC322COM',
    courseName: 'Elective I Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A3', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 135,
    facultyName: 'Prof. U. B. Karanje',
    className: 'TE',
    divisionName: 'A',
    batchName: 'A4',
    location: 'C108',
    courseCode: 'PEC322COM',
    courseName: 'Elective I Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'A4', roomNumber: 'C108', isPreferred: true }]
  },
  {
    srNo: 136,
    facultyName: 'Prof. T. S. Bhoye',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'C103',
    courseCode: 'ELC342COM',
    courseName: 'Technical Seminar',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'C103', isPreferred: true }]
  },
  {
    srNo: 137,
    facultyName: 'Prof. Y. P. Warke',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'C105',
    courseCode: 'ELC342COM',
    courseName: 'Technical Seminar',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'C105', isPreferred: true }, { batch: 'B2', roomNumber: 'C105', isPreferred: true }]
  },
  {
    srNo: 138,
    facultyName: 'Dr. S. S. Chaudhari (TPC)',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'C106',
    courseCode: 'ELC342COM',
    courseName: 'Technical Seminar',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'C106', isPreferred: true }, { batch: 'B3', roomNumber: 'C106', isPreferred: true }]
  },
  {
    srNo: 139,
    facultyName: 'Prof. Niraml B. L.',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'E101',
    courseCode: 'ELC342COM',
    courseName: 'Technical Seminar',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'E101', isPreferred: true }, { batch: 'B4', roomNumber: 'E104', isPreferred: true }]
  },
  {
    srNo: 140,
    facultyName: 'Prof. Barangale Shraddha',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'C103',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'C103', isPreferred: true }, { batch: 'B1', roomNumber: 'E103', isPreferred: true }]
  },
  {
    srNo: 141,
    facultyName: 'Prof. Barangale Shraddha',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'E103',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 0,
    tutorial: 2,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'E103', isPreferred: true }, { batch: 'B1', roomNumber: 'C103', isPreferred: true }]
  },
  {
    srNo: 142,
    facultyName: 'Prof. Barangale Shraddha',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'C103',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'C103', isPreferred: true }, { batch: 'B2', roomNumber: 'E103', isPreferred: true }]
  },
  {
    srNo: 143,
    facultyName: 'Prof. Barangale Shraddha',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'E103',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 0,
    tutorial: 2,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'E103', isPreferred: true }, { batch: 'B2', roomNumber: 'C103', isPreferred: true }]
  },
  {
    srNo: 144,
    facultyName: 'Prof. Nutan Sarode',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'E103',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'E103', isPreferred: true }, { batch: 'B3', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 145,
    facultyName: 'Prof. Nutan Sarode',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'E103',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 0,
    tutorial: 2,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'E103', isPreferred: true }, { batch: 'B3', roomNumber: 'C104', isPreferred: true }]
  },
  {
    srNo: 146,
    facultyName: 'Prof. Nutan Sarode',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'C106',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'C106', isPreferred: true }, { batch: 'B4', roomNumber: 'E103', isPreferred: true }]
  },
  {
    srNo: 147,
    facultyName: 'Prof. Nutan Sarode',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'E103',
    courseCode: 'MDM331COM',
    courseName: 'Robotics and Automation',
    theory: 0,
    practical: 0,
    tutorial: 2,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'E103', isPreferred: true }, { batch: 'B4', roomNumber: 'C106', isPreferred: true }]
  },
  {
    srNo: 148,
    facultyName: 'Dr. J. P. Shinde',
    className: 'TE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: 'OLE341COM',
    courseName: 'Open Elective',
    theory: 2,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 149,
    facultyName: 'Prof. Y. P. Warke',
    className: 'TE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: 'PCC301COM',
    courseName: 'Artificial Intelligence',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 150,
    facultyName: 'Prof. T. S. Bhoye',
    className: 'TE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: 'PCC302COM',
    courseName: 'Computer Networks',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 151,
    facultyName: 'Dr. S. K. Patil',
    className: 'TE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: 'PCC303COM',
    courseName: 'Theory of Computation',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 152,
    facultyName: 'Prof. Y. P. Warke',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'C110',
    courseCode: 'PCC304COM',
    courseName: 'Artificial Intelligence Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'C110', isPreferred: true }]
  },
  {
    srNo: 153,
    facultyName: 'Prof. Y. P. Warke',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'C110',
    courseCode: 'PCC304COM',
    courseName: 'Artificial Intelligence Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'C110', isPreferred: true }]
  },
  {
    srNo: 154,
    facultyName: 'Prof. Y. P. Warke',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'C110',
    courseCode: 'PCC304COM',
    courseName: 'Artificial Intelligence Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'C110', isPreferred: true }]
  },
  {
    srNo: 155,
    facultyName: 'Prof. Y. P. Warke',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'C110',
    courseCode: 'PCC304COM',
    courseName: 'Artificial Intelligence Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'C110', isPreferred: true }]
  },
  {
    srNo: 156,
    facultyName: 'Prof. T. S. Bhoye',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'C103',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'C103', isPreferred: true }, { batch: 'B1', roomNumber: 'C102', isPreferred: true }]
  },
  {
    srNo: 157,
    facultyName: 'Dr. J. P. Shinde',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B1',
    location: '-',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 158,
    facultyName: 'Prof. T. S. Bhoye',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'C103',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'C103', isPreferred: true }, { batch: 'B2', roomNumber: 'C102', isPreferred: true }]
  },
  {
    srNo: 159,
    facultyName: 'Dr. J. P. Shinde',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B2',
    location: '-',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 160,
    facultyName: 'Prof. T. S. Bhoye',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'C101',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'C101', isPreferred: true }, { batch: 'B3', roomNumber: 'C103', isPreferred: true }]
  },
  {
    srNo: 161,
    facultyName: 'Dr. J. P. Shinde',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B3',
    location: '-',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: []
  },
  {
    srNo: 162,
    facultyName: 'Prof. T. S. Bhoye',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'C103',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'C103', isPreferred: true }, { batch: 'B4', roomNumber: 'C101', isPreferred: true }]
  },
  {
    srNo: 163,
    facultyName: 'Prof. S. A. Agrawal',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'C103',
    courseCode: 'PCC305COM',
    courseName: 'Computer Networks Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'C103', isPreferred: true }, { batch: 'B4', roomNumber: 'C101', isPreferred: true }]
  },
  {
    srNo: 164,
    facultyName: 'Dr. P. B. Dhamdhere',
    className: 'TE',
    divisionName: 'B',
    batchName: 'All',
    location: '-',
    courseCode: 'PEC321COM',
    courseName: 'Elective I',
    theory: 3,
    practical: 0,
    tutorial: 0,
    project: 0,
    total: 3,
    allowedLocationsList: []
  },
  {
    srNo: 165,
    facultyName: 'Dr. P. B. Dhamdhere',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B1',
    location: 'C106',
    courseCode: 'PEC322COM',
    courseName: 'Elective I Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B1', roomNumber: 'C106', isPreferred: true }]
  },
  {
    srNo: 166,
    facultyName: 'Dr. P. B. Dhamdhere',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B2',
    location: 'C106',
    courseCode: 'PEC322COM',
    courseName: 'Elective I Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B2', roomNumber: 'C106', isPreferred: true }]
  },
  {
    srNo: 167,
    facultyName: 'Dr. P. B. Dhamdhere',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B3',
    location: 'C106',
    courseCode: 'PEC322COM',
    courseName: 'Elective I Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B3', roomNumber: 'C106', isPreferred: true }]
  },
  {
    srNo: 168,
    facultyName: 'Dr. P. B. Dhamdhere',
    className: 'TE',
    divisionName: 'B',
    batchName: 'B4',
    location: 'C106',
    courseCode: 'PEC322COM',
    courseName: 'Elective I Lab',
    theory: 0,
    practical: 2,
    tutorial: 0,
    project: 0,
    total: 2,
    allowedLocationsList: [{ batch: 'B4', roomNumber: 'C106', isPreferred: true }]
  },
];
